import { ref, computed } from 'vue'

export const currentLanguage = ref('EN')
export const setLanguage = (lang) => { currentLanguage.value = lang }

export const translations = {
  EN: {
    home: 'Home',
    about: 'About',
    services: 'Services',
    gallery: 'Gallery',
    photos: 'Photos',
    videos: 'Videos',
    destination: 'Destination',
    northern: 'Northern',
    southern: 'Southern',
    eastern: 'Eastern',
    western: 'Western',
    kigali: 'Kigali',
    contact: 'Contact',
    language: 'Language:',
    login: 'Login',
    register: 'Register',
    homeTitle: 'Welcome to Rwanda',
    homeSubtitle: 'the Land of a Thousand Hills',
    discover: 'Discover Rwanda',
    nature: 'Nature & Parks',
    travelTips: 'Travel Tips',
    planTrip: 'Plan your trip',
    aboutHeading: 'Explore Rwanda with ease and confidence.',
    aboutLead: 'A beginner-friendly guide for travelers who want to experience Rwanda’s beauty, culture, and wildlife. Discover simple planning tips, top destinations, and local experiences designed for first-time visitors.',
    contactHeading: 'Get in Touch with Tembera Urwanda',
    contactLead: "We're here to help plan your perfect Rwanda adventure. Reach out anytime for itinerary planning, booking support, or local travel advice."
  },
  FR: {
    home: 'Accueil',
    about: 'À propos',
    services: 'Services',
    gallery: 'Galerie',
    photos: 'Photos',
    videos: 'Vidéos',
    destination: 'Destination',
    northern: 'Nord',
    southern: 'Sud',
    eastern: 'Est',
    western: 'Ouest',
    kigali: 'Kigali',
    contact: 'Contact',
    language: 'Langue:',
    login: 'Connexion',
    register: 'Inscription',
    homeTitle: 'Bienvenue au Rwanda',
    homeSubtitle: 'le pays des mille collines',
    discover: 'Découvrez le Rwanda',
    nature: 'Nature et Parcs',
    travelTips: 'Conseils de voyage',
    planTrip: 'Planifiez votre voyage',
    aboutHeading: 'Explorez le Rwanda en toute simplicité.',
    aboutLead: 'Un guide convivial pour les voyageurs qui souhaitent découvrir la beauté, la culture et la faune du Rwanda. Découvrez des conseils de planification simples, les principales destinations et des expériences locales conçues pour les visiteurs débutants.',
    contactHeading: 'Contactez Tembera Urwanda',
    contactLead: 'Nous sommes ici pour vous aider à planifier votre voyage parfait au Rwanda. Contactez-nous à tout moment pour la planification d\'itinéraire, le support de réservation ou des conseils de voyage locaux.'
  },
  RW: {
    home: 'Ahabanza',
    about: 'Ibyerekeye',
    services: 'Serivisi',
    gallery: 'Ibyerekanwa',
    photos: 'Amafoto',
    videos: 'Amashusho',
    destination: 'Ahantu',
    northern: 'Amajyaruguru',
    southern: 'Amajyepfo',
    eastern: 'Iburasirazuba',
    western: 'Uburengerazuba',
    kigali: 'Kigali',
    contact: 'Vega',
    language: 'Ururimi:',
    login: 'Injira',
    register: 'Iyandikishe',
    homeTitle: 'Murakaza neza mu Rwanda',
    homeSubtitle: 'Igihugu cy\'ahantu henshi h\'urutare',
    discover: 'Menya byinshi ku Rwanda',
    nature: "Ibidukikije n'amaparike",
    travelTips: 'Inama z\'ingendo',
    planTrip: 'Tegura urugendo rwawe',
    aboutHeading: 'Sura u Rwanda byoroshye.',
    aboutLead: 'Umuyobozi worohereza abagenzi bashaka gukurikirana ubwiza, umuco n\'inyamaswa z\'u Rwanda. Menya inama zoroshye zo gutegura urugendo, ahantu nyaburanga n\'ibikorwa by\'aho byateguwe ku bashyitsi b\'imbere.',
    contactHeading: 'Twandikire Tembera Urwanda',
    contactLead: 'Duhari kugirango tugufashe gutegura urugendo rwawe rwiza mu Rwanda. Twandikire igihe cyose ku bijyanye no gutegura inzira, gufasha mu kubika cyangwa inama z\'ingendo.'
  }
}

export const labels = computed(() => translations[currentLanguage.value] || translations.EN)
